name: Run Gradle Tests In Docker Container CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build_On_MySQL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Container start
        run: docker-compose up &
      - name: Waiting for container start
        run: sleep 30
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT on mySQL
        run: java -jar ./artifacts/aqa-shop.jar &
      - name: Build with Gradle
        run: ./gradlew clean test --info -Dselenide.headless=true
  #       Команда ниже закрывает приложение "aqa-shop.jar"
  #      - name: Exit Java JAR
  #        run: pkill java

  Build_On_PostgreSQL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Container start
        run: docker-compose up &
      - name: Waiting for container start
        run: sleep 30
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT on PostgreSQL
        run: java "-Dspring.datasource.url=jdbc:postgresql://localhost:5432/app" -jar artifacts/aqa-shop.jar &
      - name: Build with Gradle
        run: ./gradlew clean test "-Ddb.url=jdbc:postgresql://localhost:5432/app" --info -Dselenide.headless=true