name: Run Gradle Tests In Docker Container CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Container start
        run: docker-compose up &
      - name: Waiting for —Åontainer start
        run: sleep 30
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
        run: java -jar ./artifacts/app-deadline.jar &
      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true